export type SelectedLocation = {
  latitude: number;
  longitude: number;
  country?: {
    name: string;
    code: string;
  };
  wildlifeObservations?: WildlifeObservation[];
};

// Wildlife types autogenerated by Cursor based on an API response
export type GeoJSON = {
  type: 'Point';
  coordinates: [number, number]; // [longitude, latitude]
};

export type Photo = {
  id: number;
  attribution: string;
  license_code: string;
  url: string;
  original_dimensions: {
    width: number;
    height: number;
  };
  flags: unknown[];
  hidden: boolean;
  moderator_actions: unknown[];
};

export type Taxon = {
  is_active: boolean;
  ancestry: string;
  min_species_ancestry: string;
  endemic: boolean;
  iconic_taxon_id: number;
  // Add other taxon properties as needed
};

export type User = {
  id: number;
  login: string;
  spam: boolean;
  suspended: boolean;
  created_at: string;
};

export type Identification = {
  id: number;
  uuid: string;
  user: User;
  taxon: Taxon;
  current: boolean;
  created_at: string;
  created_at_details: {
    date: string;
    day: number;
    month: number;
    year: number;
  };
  updated_at: string;
  body: string | null;
  category: string;
  disagreement: boolean | null;
  previous_observation_taxon_id: number | null;
  vision: boolean;
  disabled: boolean;
  spam: boolean;
  taxon_change: unknown | null;
};

export type WildlifeObservation = {
  id: number;
  uuid: string;
  observed_on: string;
  observed_on_string: string;
  observed_on_details: {
    date: string;
    day: number;
    month: number;
    year: number;
    hour?: number;
  };
  time_observed_at: string;
  time_zone_offset: string;
  observed_time_zone: string;
  created_at: string;
  created_at_details: {
    date: string;
    day: number;
    month: number;
    year: number;
    hour: number;
  };
  created_time_zone: string;
  updated_at: string;
  location: string; // "latitude,longitude"
  geojson: GeoJSON;
  place_guess: string;
  place_ids: number[];
  positional_accuracy: number;
  public_positional_accuracy: number;
  geoprivacy: string | null;
  taxon_geoprivacy: string;
  quality_grade: string;
  quality_metrics: unknown[];
  identifications_most_agree: boolean;
  identifications_most_disagree: boolean;
  identifications_count: number;
  identifications_some_agree: boolean;
  num_identification_agreements: number;
  num_identification_disagreements: number;
  identification_disagreements_count: number;
  ident_taxon_ids: number[];
  community_taxon_id: number | null;
  species_guess: string;
  taxon: Taxon;
  user: User;
  photos: Photo[];
  observation_photos: Photo[];
  identifications: Identification[];
  faves: unknown[];
  faves_count: number;
  comments: unknown[];
  comments_count: number;
  tags: string[];
  description: string;
  license_code: string;
  captive: boolean;
  obscured: boolean;
  mappable: boolean;
  map_scale: number | null;
  annotations: unknown[];
  cached_votes_total: number;
  flags: unknown[];
  spam: boolean;
  project_ids: number[];
  project_observations: unknown[];
  reviewed_by: number[];
  site_id: number;
  sounds: unknown[];
  ofvs: unknown[];
  outlinks: Array<{
    source: string;
    url: string;
  }>;
  owners_identification_from_vision: boolean;
  non_owner_ids: Identification[];
  preferences: {
    prefers_community_taxon: string | null;
  };
  uri: string;
  oauth_application_id: number;
};

export type ObservationResponse = {
  total_results: number;
  page: number;
  per_page: number;
  results: WildlifeObservation[];
};
